#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Gets provenance for a package version.

API:  GET {org}/_apis/packaging/Feeds/{feed_id}/Packages/{package_id}/Versions/{package_version_id}/provenance?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact--details/get-package-version-provenance?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
FEED_ID = get_env_or_exit("FEED_ID", "Name or Id of the feed.")
PACKAGE_ID = get_env_or_exit("PACKAGE_ID", "Id of the package (GUID Id, not name).")
PACKAGE_VERSION_ID = get_env_or_exit("PACKAGE_VERSION_ID", "Id of the package version (GUID Id, not name).")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("get_packageversionprovenance", PAT)
logger.info("Gets provenance for a package version.")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/packaging/Feeds/{FEED_ID}/Packages/{PACKAGE_ID}/Versions/{PACKAGE_VERSION_ID}/provenance", API_VERSION, project=PROJECT_ID, base_host="feeds.dev.azure.com")
logger.info(f"GET {url}")

response = execute_request("GET", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['feedId', 'packageId'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
