#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update a subscription.

API:  PUT {org}/_apis/hooks/subscriptions/{subscription_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/hooks/subscriptions/replace-subscription?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
SUBSCRIPTION_ID = get_env_or_exit("SUBSCRIPTION_ID", "subscriptionId")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update a subscription.")
parser.add_argument("--action-description", required=False, help="actionDescription")
parser.add_argument("--consumer-action-id", required=False, help="consumerActionId")
parser.add_argument("--consumer-id", required=False, help="consumerId")
parser.add_argument("--consumer-inputs", required=False, help="Consumer input values")
parser.add_argument("--created-by", required=False, help="createdBy")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("set_replace_subscription", PAT)
logger.info("Update a subscription.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "actionDescription": args.action_description,
    "consumerActionId": args.consumer_action_id,
    "consumerId": args.consumer_id,
    "consumerInputs": args.consumer_inputs,
    "createdBy": args.created_by,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/hooks/subscriptions/{SUBSCRIPTION_ID}", API_VERSION)
logger.info(f"PUT {url}")

response = execute_request("PUT", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['id', 'actionDescription'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
