#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Returns a behavior for the work item type of the process.
#
# API:  GET {org}/_apis/work/processes/{process_id}/workitemtypesbehaviors/{wit_ref_name_for_behaviors}/behaviors/{behavior_ref_name}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" WIT_REF_NAME_FOR_BEHAVIORS="value" BEHAVIOR_REF_NAME="value" bash get_work_item_types_behaviors.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/work-item-types-behaviors/get?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "The ID of the process")
WIT_REF_NAME_FOR_BEHAVIORS=$(ado_require_env "WIT_REF_NAME_FOR_BEHAVIORS" "Work item type reference name for the behavior")
BEHAVIOR_REF_NAME=$(ado_require_env "BEHAVIOR_REF_NAME" "The reference name of the behavior")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processes/${PROCESS_ID}/workitemtypesbehaviors/${WIT_REF_NAME_FOR_BEHAVIORS}/behaviors/${BEHAVIOR_REF_NAME}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "behavior" "isDefault"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
