#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update timeline records if they already exist, otherwise create new ones for the same timeline.

API:  PATCH {org}/{scope_identifier}/_apis/distributedtask/hubs/{hub_name}/plans/{plan_id}/timelines/{timeline_id}/records?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/records/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
SCOPE_IDENTIFIER = get_env_or_exit("SCOPE_IDENTIFIER", "The project GUID to scope the request")
HUB_NAME = get_env_or_exit("HUB_NAME", "The name of the server hub. Common examples: 'build', 'rm', 'checks'")
PLAN_ID = get_env_or_exit("PLAN_ID", "The ID of the plan.")
TIMELINE_ID = get_env_or_exit("TIMELINE_ID", "The ID of the timeline.")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update timeline records if they already exist, otherwise create new ones for the same timeline.")
parser.add_argument("--value", required=False, help="The serialized item.")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_records", PAT)
logger.info("Update timeline records if they already exist, otherwise create new ones for the same timeline.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "value": args.value,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"{SCOPE_IDENTIFIER}/_apis/distributedtask/hubs/{HUB_NAME}/plans/{PLAN_ID}/timelines/{TIMELINE_ID}/records", API_VERSION)
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
