#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update timeline records if they already exist, otherwise create new ones for the same timeline.
#
# API:  PATCH {org}/{scope_identifier}/_apis/distributedtask/hubs/{hub_name}/plans/{plan_id}/timelines/{timeline_id}/records?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: SCOPE_IDENTIFIER="value" HUB_NAME="value" PLAN_ID="value" TIMELINE_ID="value" bash update_records.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/records/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
SCOPE_IDENTIFIER=$(ado_require_env "SCOPE_IDENTIFIER" "The project GUID to scope the request")
HUB_NAME=$(ado_require_env "HUB_NAME" "The name of the server hub. Common examples: 'build', 'rm', 'checks'")
PLAN_ID=$(ado_require_env "PLAN_ID" "The ID of the plan.")
TIMELINE_ID=$(ado_require_env "TIMELINE_ID" "The ID of the timeline.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "value": "${VALUE}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "${SCOPE_IDENTIFIER}/_apis/distributedtask/hubs/${HUB_NAME}/plans/${PLAN_ID}/timelines/${TIMELINE_ID}/records" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
