# AUTO-GENERATED by _generator — do not edit by hand.
<#
.SYNOPSIS
    Pester offline unit tests for Get-Subscriptions.ps1

.DESCRIPTION
    Mocks Invoke-RestMethod to validate URL construction,
    auth headers, response parsing, and error handling.
#>

BeforeAll {
    $ScriptPath = Join-Path $PSScriptRoot '..' 'Get-Subscriptions.ps1'
    $FixturePath = Join-Path $PSScriptRoot 'fixtures'
}

Describe 'Get-Subscriptions.ps1' -Tag 'Offline', 'Notification' {

    Context 'Input validation' {

        It 'Throws when Organisation is empty' {
            {
                & $ScriptPath -Organization '' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when Pat is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Pat ''
            } | Should -Throw '*is required*'
        }
    }

    Context 'Successful API call (mocked)' {

        BeforeAll {
            $fixture = Get-Content (Join-Path $FixturePath 'list_subscriptions_200.json') -Raw | ConvertFrom-Json
        }

        It 'Calls the correct URL' {
            Mock Invoke-RestMethod { return $fixture } -Verifiable

            & $ScriptPath -Organization 'testorg' -Pat 'fakepat' | Out-Null

            Should -InvokeVerifiable
            Should -Invoke Invoke-RestMethod -Times 1 -Exactly -ParameterFilter {
                $Uri -eq "https://{service}dev.azure.com/testorg/_apis/notification/subscriptions?api-version=7.2" -and
                $Method -eq 'Get'
            }
        }

        It 'Sends correct Authorization header' {
            $expectedAuth = [Convert]::ToBase64String(
                [Text.Encoding]::ASCII.GetBytes(':fakepat')
            )

            Mock Invoke-RestMethod { return $fixture }

            & $ScriptPath -Organization 'testorg' -Pat 'fakepat' | Out-Null

            Should -Invoke Invoke-RestMethod -Times 1 -ParameterFilter {
                $Headers['Authorization'] -eq "Basic $expectedAuth"
            }
        }
    }

    Context 'HTTP error handling' {

        It 'Throws on 404 (not found)' {
            Mock Invoke-RestMethod {
                $ex = [System.Net.WebException]::new('The remote server returned an error: (404) Not Found.')
                throw $ex
            }

            { & $ScriptPath -Organization 'testorg' -Pat 'fakepat' } | Should -Throw
        }
    }
}
