# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Removes a behavior for the work item type of the process.

.DESCRIPTION
    Calls  DELETE {org}/_apis/work/processdefinitions/{process_id}/workitemtypes/{wit_ref_name_for_behaviors}/behaviors/{behavior_ref_name}?api-version=4.1
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/process-definitions/remove-behavior-from-work-item-type/remove-behavior-from-work-item-type?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProcessId = $env:PROCESS_ID,

    [Parameter()]
    [string]$WitRefNameForBehaviors = $env:WIT_REF_NAME_FOR_BEHAVIORS,

    [Parameter()]
    [string]$BehaviorRefName = $env:BEHAVIOR_REF_NAME,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProcessId' -Value $ProcessId
Assert-AdoEnv -Name 'WitRefNameForBehaviors' -Value $WitRefNameForBehaviors
Assert-AdoEnv -Name 'BehaviorRefName' -Value $BehaviorRefName
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '4.1'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/work/processdefinitions/$ProcessId/workitemtypes/$WitRefNameForBehaviors/behaviors/$BehaviorRefName" -ApiVersion $ApiVersion

Write-Verbose "DELETE $uri"

$response = Invoke-RestMethod -Uri $uri -Method Delete -Headers $headers -ContentType 'application/json'

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
