# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Revokes the listed OAuth authorizations.

.DESCRIPTION
    Calls  POST {org}/_apis/tokenadministration/tokenrevocations?api-version=5.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/token-administration/revoke-authorizations/revoke-authorizations?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$Audience,

    [Parameter(Mandatory)]
    [string]$AuthorizationIds,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$HostId = $env:HOST_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'HostId' -Value $HostId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '5.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    audience = $Audience
    authorizationIds = $AuthorizationIds
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/tokenadministration/tokenrevocations" -ApiVersion $ApiVersion

Write-Verbose "POST $uri"

$response = Invoke-AdoRestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ExpectedStatusCode 204

#--- Output -----------------------------------------------------------------
if ($response.StatusCode -eq 204) {
    Write-Host "Revoke Authorizations operation completed successfully."
} else {
    Write-Warning "Unexpected status code: $($response.StatusCode)"
}
