# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Replaces a behavior in the process.

.DESCRIPTION
    Calls  PUT {org}/_apis/work/processdefinitions/{process_id}/behaviors/{behavior_id}?api-version=4.1
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/process-definitions/replace-behavior/replace-behavior?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$Color,

    [Parameter(Mandatory)]
    [string]$Name,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProcessId = $env:PROCESS_ID,

    [Parameter()]
    [string]$BehaviorId = $env:BEHAVIOR_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProcessId' -Value $ProcessId
Assert-AdoEnv -Name 'BehaviorId' -Value $BehaviorId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '4.1'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    color = $Color
    name = $Name
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/work/processdefinitions/$ProcessId/behaviors/$BehaviorId" -ApiVersion $ApiVersion

Write-Verbose "PUT $uri"

$response = Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'id') {
    Write-Warning "Unexpected response shape — missing 'id'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'name') {
    Write-Warning "Unexpected response shape — missing 'name'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'abstract') {
    Write-Warning "Unexpected response shape — missing 'abstract'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Replace Behavior: $($response.name)"
$response | ConvertTo-Json -Depth 5
