#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Delete a policy configuration by its ID.

API:  DELETE {org}/_apis/policy/configurations/{configuration_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/delete?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
CONFIGURATION_ID = get_env_or_exit("CONFIGURATION_ID", "ID of the policy configuration to delete.")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("delete_configurations", PAT)
logger.info("Delete a policy configuration by its ID.")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/policy/configurations/{CONFIGURATION_ID}", API_VERSION, project=PROJECT_ID)
logger.info(f"DELETE {url}")

response = execute_request("DELETE", url, HEADERS, expected_status=204)

# ---------------------------------------------------------------------------
# Output — DELETE returns 204 No Content on success
# ---------------------------------------------------------------------------
if response.status_code == 204:
    logger.info("Configurations operation completed successfully.")
    print("Configurations operation completed successfully.")
else:
    logger.error(f"Unexpected status code: {response.status_code}")
    print(f"Unexpected status code: {response.status_code}", file=sys.stderr)
    if response.text:
        print(response.text)
