#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update team field values

API:  PATCH {org}/{team}/_apis/work/teamsettings/teamfieldvalues?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/work/teamfieldvalues/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
TEAM_ID = get_env_or_exit("TEAM_ID", "Team ID or team name")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update team field values")
parser.add_argument("--default-value", required=False, help="defaultValue")
parser.add_argument("--values", required=False, help="values")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_teamfieldvalues", PAT)
logger.info("Update team field values")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "defaultValue": args.default_value,
    "values": args.values,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"{TEAM_ID}/_apis/work/teamsettings/teamfieldvalues", API_VERSION, project=PROJECT_ID)
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['defaultValue', 'field'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
