# AUTO-GENERATED by _generator — do not edit by hand.
<#
.SYNOPSIS
    Pester offline unit tests for Update-Record.ps1

.DESCRIPTION
    Mocks Invoke-RestMethod to validate URL construction,
    auth headers, response parsing, and error handling.
#>

BeforeAll {
    $ScriptPath = Join-Path $PSScriptRoot '..' 'Update-Record.ps1'
    $FixturePath = Join-Path $PSScriptRoot 'fixtures'
}

Describe 'Update-Record.ps1' -Tag 'Offline', 'DistributedTask' {

    Context 'Input validation' {

        It 'Throws when Organisation is empty' {
            {
                & $ScriptPath -Organization '' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when ScopeIdentifier is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier '' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when HubName is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName '' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when PlanId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId '' -TimelineId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when TimelineId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId '' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when Pat is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat ''
            } | Should -Throw '*is required*'
        }
    }

    Context 'Successful API call (mocked)' {

        BeforeAll {
            $fixture = Get-Content (Join-Path $FixturePath 'update_records_200.json') -Raw | ConvertFrom-Json
        }

        It 'Calls the correct URL' {
            Mock Invoke-RestMethod { return $fixture } -Verifiable

            & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -InvokeVerifiable
            Should -Invoke Invoke-RestMethod -Times 1 -Exactly -ParameterFilter {
                $Uri -eq "https://dev.azure.com/testorg/testvalue/_apis/distributedtask/hubs/testvalue/plans/testvalue/timelines/testvalue/records?api-version=7.2" -and
                $Method -eq 'Patch'
            }
        }

        It 'Sends correct Authorization header' {
            $expectedAuth = [Convert]::ToBase64String(
                [Text.Encoding]::ASCII.GetBytes(':fakepat')
            )

            Mock Invoke-RestMethod { return $fixture }

            & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -Invoke Invoke-RestMethod -Times 1 -ParameterFilter {
                $Headers['Authorization'] -eq "Basic $expectedAuth"
            }
        }
    }

    Context 'HTTP error handling' {

        It 'Throws on 404 (not found)' {
            Mock Invoke-RestMethod {
                $ex = [System.Net.WebException]::new('The remote server returned an error: (404) Not Found.')
                throw $ex
            }

            { & $ScriptPath -Organization 'testorg' -Value 'testvalue' -ScopeIdentifier 'testvalue' -HubName 'testvalue' -PlanId 'testvalue' -TimelineId 'testvalue' -Pat 'fakepat' } | Should -Throw
        }
    }
}
