#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
List commits in a Git repository.

API:  GET {org}/_apis/git/repositories/{repository_id}/commits?api-version=7.2-preview.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/commits/get-commits?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2-preview.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
REPOSITORY_ID = get_env_or_exit("REPOSITORY_ID", "Repository name or GUID")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("list_commits", PAT)
logger.info("List commits in a Git repository.")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/git/repositories/{REPOSITORY_ID}/commits", API_VERSION, project=PROJECT_ID)
logger.info(f"GET {url}")

response = execute_request("GET", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['count', 'value'], API_VERSION)

logger.info(f"Retrieved {data.get('count', '?')} items")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(f"Total: {data.get('count', 'N/A')}\n")
for item in data.get("value", []):
    cols = [item.get("commitId", "N/A"), item.get("comment", "N/A")]
    print("  " + "  ".join(str(c) for c in cols))
