#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Updates a given state definition in the work item type of the process.
#
# API:  PATCH {org}/_apis/work/processes/{process_id}/workItemTypes/{wit_ref_name}/states/{state_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" WIT_REF_NAME="value" STATE_ID="value" bash update_states.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/states/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "ID of the process")
WIT_REF_NAME=$(ado_require_env "WIT_REF_NAME" "The reference name of the work item type")
STATE_ID=$(ado_require_env "STATE_ID" "ID of the state")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "color": "${COLOR}",
  "name": "${NAME}",
  "order": "${ORDER}",
  "stateCategory": "${STATE_CATEGORY}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processes/${PROCESS_ID}/workItemTypes/${WIT_REF_NAME}/states/${STATE_ID}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "name" "color"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "States: {name}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
