#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Triggers a pipeline run of pipelines which have a webhook resource defined with specified WebHook Name property of th...

API:  POST {org}/_apis/public/distributedtask/webhooks/{web_hook_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/webhooks/receive-external-event?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
WEB_HOOK_ID = get_env_or_exit("WEB_HOOK_ID", "The WebHook Name property of the WebHook service connection")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_receive_external_event", PAT)
logger.info("Triggers a pipeline run of pipelines which have a webhook resource defined with specified WebHook Name property of th...")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/public/distributedtask/webhooks/{WEB_HOOK_ID}", API_VERSION)
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
