#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Creates an attachment in the LogStore for the specified runId.

API:  POST {org}/_apis/testresults/runs/{run_id}/testattachments?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/test-results/testattachments/create-test-run-log-store-attachment?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
RUN_ID = get_env_or_exit("RUN_ID", "Test RunId")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Creates an attachment in the LogStore for the specified runId.")
parser.add_argument("--attachment-type", required=False, help="Attachment type By Default it will be GeneralAttachment. It can be one of the following type. { G...")
parser.add_argument("--comment", required=False, help="Comment associated with attachment")
parser.add_argument("--file-name", required=False, help="Attachment filename")
parser.add_argument("--stream", required=False, help="Base64 encoded file stream")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_test_run_log_store_attachment", PAT)
logger.info("Creates an attachment in the LogStore for the specified runId.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "attachmentType": args.attachment_type,
    "comment": args.comment,
    "fileName": args.file_name,
    "stream": args.stream,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/testresults/runs/{RUN_ID}/testattachments", API_VERSION, project=PROJECT_ID, base_host="vstmr.dev.azure.com")
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['url'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
