#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update agent details.
#
# API:  PATCH {org}/_apis/distributedtask/pools/{pool_id}/agents/{agent_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: POOL_ID="value" AGENT_ID="value" bash update_agents.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/agents/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
POOL_ID=$(ado_require_env "POOL_ID" "The agent pool to use")
AGENT_ID=$(ado_require_env "AGENT_ID" "The agent to update")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "assignedAgentCloudRequest": "${ASSIGNED_AGENT_CLOUD_REQUEST}",
  "assignedRequest": "${ASSIGNED_REQUEST}",
  "authorization": "${AUTHORIZATION}",
  "createdOn": "${CREATED_ON}",
  "lastCompletedRequest": "${LAST_COMPLETED_REQUEST}",
  "maxParallelism": "${MAX_PARALLELISM}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/distributedtask/pools/${POOL_ID}/agents/${AGENT_ID}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "assignedAgentCloudRequest" "assignedRequest"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
