# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Create new Audit Stream

.DESCRIPTION
    Calls  POST {org}/_apis/audit/streams?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/audit/streams/create?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$ConsumerInputs,

    [Parameter(Mandatory)]
    [string]$ConsumerType,

    [Parameter(Mandatory)]
    [string]$CreatedTime,

    [Parameter(Mandatory)]
    [string]$DisplayName,

    [Parameter(Mandatory)]
    [string]$Id,

    [Parameter(Mandatory)]
    [string]$Status,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$DaysToBackfill = $env:DAYS_TO_BACKFILL,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'DaysToBackfill' -Value $DaysToBackfill
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    consumerInputs = $ConsumerInputs
    consumerType = $ConsumerType
    createdTime = $CreatedTime
    displayName = $DisplayName
    id = $Id
    status = $Status
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/audit/streams" -ApiVersion $ApiVersion -BaseHost "auditservice.dev.azure.com"

Write-Verbose "POST $uri"

$response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'id') {
    Write-Warning "Unexpected response shape — missing 'id'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'consumerInputs') {
    Write-Warning "Unexpected response shape — missing 'consumerInputs'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Streams ID: $($response.id)"
$response | ConvertTo-Json -Depth 5
