#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Return Audit Stream with id of streamId if one exists otherwise throw
#
# API:  GET {org}/_apis/audit/streams/{stream_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: STREAM_ID="value" bash query_stream_by_id.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/audit/streams/query-stream-by-id?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
STREAM_ID=$(ado_require_env "STREAM_ID" "Id of stream entry to retrieve")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/audit/streams/${STREAM_ID}" "$API_VERSION" "" "auditservice.dev.azure.com")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "consumerInputs"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Streams ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
