# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Returns a single update for a work item

.DESCRIPTION
    Calls  GET {org}/_apis/wit/workItems/{id}/updates/{update_number}?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/updates/get?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProjectId = $env:PROJECT_ID,

    [Parameter()]
    [string]$Id = $env:RESOURCE_ID,

    [Parameter()]
    [string]$UpdateNumber = $env:UPDATE_NUMBER,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProjectId' -Value $ProjectId
Assert-AdoEnv -Name 'Id' -Value $Id
Assert-AdoEnv -Name 'UpdateNumber' -Value $UpdateNumber
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/wit/workItems/$Id/updates/$UpdateNumber" -ApiVersion $ApiVersion -Project $ProjectId

Write-Verbose "GET $uri"

$response = Invoke-RestMethod -Uri $uri -Method Get -Headers $headers -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'id') {
    Write-Warning "Unexpected response shape — missing 'id'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'fields') {
    Write-Warning "Unexpected response shape — missing 'fields'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Updates ID: $($response.id)"
$response | ConvertTo-Json -Depth 5
