#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update the properties of an Azure DevOps group.

API:  PATCH {org}/_apis/graph/groups/{group_descriptor}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/groups/update?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
GROUP_DESCRIPTOR = get_env_or_exit("GROUP_DESCRIPTOR", "The descriptor of the group to modify.")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_groups", PAT)
logger.info("Update the properties of an Azure DevOps group.")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/graph/groups/{GROUP_DESCRIPTOR}", API_VERSION, base_host="vssps.dev.azure.com")
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['description'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
