#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Replaces a behavior in the process.
#
# API:  PUT {org}/_apis/work/processes/{process_id}/behaviors/{behavior_ref_name}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" BEHAVIOR_REF_NAME="value" bash update_behaviors.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/behaviors/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "The ID of the process")
BEHAVIOR_REF_NAME=$(ado_require_env "BEHAVIOR_REF_NAME" "The reference name of the behavior")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "color": "${COLOR}",
  "name": "${NAME}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processes/${PROCESS_ID}/behaviors/${BEHAVIOR_REF_NAME}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PUT \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "name" "color"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Behaviors: {name}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
