#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update project settings of test results

API:  PATCH {org}/_apis/testresults/settings?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/test-results/settings/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update project settings of test results")
parser.add_argument("--advanced-flaky-detection-settings", required=False, help="Advanced system flaky detection settings Contains parameter configurations for failure rate, pass...")
parser.add_argument("--flaky-settings", required=False, help="FlakySettings defines Flaky Settings Data.")
parser.add_argument("--new-test-result-logging-settings", required=False, help="NewTestResultLoggingSettings defines the setting for logging new test results")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_settings", PAT)
logger.info("Update project settings of test results")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "advancedFlakyDetectionSettings": args.advanced_flaky_detection_settings,
    "flakySettings": args.flaky_settings,
    "newTestResultLoggingSettings": args.new_test_result_logging_settings,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/testresults/settings", API_VERSION, project=PROJECT_ID, base_host="vstmr.dev.azure.com")
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['advancedFlakyDetectionSettings', 'flakySettings'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
