#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Change the attributes of a feed.
#
# API:  PATCH {org}/_apis/packaging/feeds/{feed_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: FEED_ID="value" bash update_feed.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed--management/update-feed?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
FEED_ID=$(ado_require_env "FEED_ID" "Name or Id of the feed.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "allowUpstreamNameConflict": "${ALLOW_UPSTREAM_NAME_CONFLICT}",
  "badgesEnabled": "${BADGES_ENABLED}",
  "defaultViewId": "${DEFAULT_VIEW_ID}",
  "description": "${DESCRIPTION}",
  "hideDeletedPackageVersions": "${HIDE_DELETED_PACKAGE_VERSIONS}",
  "id": "${RESOURCE_ID}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/packaging/feeds/${FEED_ID}" "$API_VERSION" "$PROJECT" "feeds.dev.azure.com")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "badgesEnabled" "defaultViewId"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
