#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Set the upstreaming behavior of a (scoped) package within the context of a feed The package does not need to necessar...

API:  PATCH {org}/_apis/packaging/feeds/{feed_id}/npm/packages/@{package_scope}/{unscoped_package_name}/upstreaming?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/artifacts-package-types/npm/set-scoped-upstreaming-behavior?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
FEED_ID = get_env_or_exit("FEED_ID", "The name or id of the feed")
PACKAGE_SCOPE = get_env_or_exit("PACKAGE_SCOPE", "The scope of the package")
UNSCOPED_PACKAGE_NAME = get_env_or_exit("UNSCOPED_PACKAGE_NAME", "The name of the scoped package")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Set the upstreaming behavior of a (scoped) package within the context of a feed The package does not need to necessar...")
parser.add_argument("--versions-from-external-upstreams", required=False, help="Indicates whether external upstream versions should be considered for this package")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("set_scoped_upstreaming_behavior", PAT)
logger.info("Set the upstreaming behavior of a (scoped) package within the context of a feed The package does not need to necessar...")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "versionsFromExternalUpstreams": args.versions_from_external_upstreams,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/packaging/feeds/{FEED_ID}/npm/packages/@{PACKAGE_SCOPE}/{UNSCOPED_PACKAGE_NAME}/upstreaming", API_VERSION, project=PROJECT_ID, base_host="pkgs.dev.azure.com")
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
