#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Retrieves a single label (tag) that has been assigned to a pull request.
#
# API:  GET {org}/_apis/git/repositories/{repository_id}/pullRequests/{pull_request_id}/labels/{label_id_or_name}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: REPO_ID="value" PULL_REQUEST_ID="value" LABEL_ID_OR_NAME="value" bash get_pull_request_labels.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-labels/get?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
REPO_ID=$(ado_require_env "REPO_ID" "The repository ID of the pull request’s target branch.")
PULL_REQUEST_ID=$(ado_require_env "PULL_REQUEST_ID" "ID of the pull request.")
LABEL_ID_OR_NAME=$(ado_require_env "LABEL_ID_OR_NAME" "The name or ID of the label requested.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/git/repositories/${REPO_ID}/pullRequests/${PULL_REQUEST_ID}/labels/${LABEL_ID_OR_NAME}" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "name" "active"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Pull Request Labels: {name}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
