# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Create empty file for a run and Get Sas uri for the file

.DESCRIPTION
    Calls  POST {org}/_apis/testresults/runs/{run_id}/testlogstoreendpoint?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/test-results/testlogstoreendpoint/test-log-store-endpoint-details-for-run?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProjectId = $env:PROJECT_ID,

    [Parameter()]
    [string]$RunId = $env:RUN_ID,

    [Parameter()]
    [string]$TestLogStoreOperationType = $env:TEST_LOG_STORE_OPERATION_TYPE,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProjectId' -Value $ProjectId
Assert-AdoEnv -Name 'RunId' -Value $RunId
Assert-AdoEnv -Name 'TestLogStoreOperationType' -Value $TestLogStoreOperationType
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/testresults/runs/$RunId/testlogstoreendpoint" -ApiVersion $ApiVersion -Project $ProjectId -BaseHost "vstmr.dev.azure.com"

Write-Verbose "POST $uri"

$response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'endpointSASUri') {
    Write-Warning "Unexpected response shape — missing 'endpointSASUri'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'endpointType') {
    Write-Warning "Unexpected response shape — missing 'endpointType'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
