#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Removes a work item type in the process.
#
# API:  DELETE {org}/_apis/work/processes/{process_id}/workitemtypes/{wit_ref_name}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" WIT_REF_NAME="value" bash delete_work_item_types.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/work-item-types/delete?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "The ID of the process.")
WIT_REF_NAME=$(ado_require_env "WIT_REF_NAME" "The reference name of the work item type.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processes/${PROCESS_ID}/workitemtypes/${WIT_REF_NAME}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X DELETE \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
