#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Creates or edits a wiki page.
#
# API:  PUT {org}/_apis/wiki/wikis/{wiki_identifier}/pages?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: WIKI_IDENTIFIER="value" PATH="value" bash create_or_update.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/wiki/pages/create-or-update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
WIKI_IDENTIFIER=$(ado_require_env "WIKI_IDENTIFIER" "Wiki ID or wiki name.")
PATH=$(ado_require_env "PATH" "Wiki page path.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "content": "${CONTENT}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/wiki/wikis/${WIKI_IDENTIFIER}/pages" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X PUT \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "gitItemPath"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Pages ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
