#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update check configuration

API:  PATCH {org}/_apis/pipelines/checks/configurations/{id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/approvals-and-checks/check-configurations/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
RESOURCE_ID = get_env_or_exit("RESOURCE_ID", "check configuration id")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update check configuration")
parser.add_argument("--created-by", required=False, help="Identity of person who configured check.")
parser.add_argument("--created-on", required=False, help="Time when check got configured.")
parser.add_argument("--is-disabled", required=False, help="Is check disabled.")
parser.add_argument("--issue", required=False, help="Issue connected to check configuration.")
parser.add_argument("--modified-by", required=False, help="Identity of person who modified the configured check.")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_check_configurations", PAT)
logger.info("Update check configuration")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "createdBy": args.created_by,
    "createdOn": args.created_on,
    "isDisabled": args.is_disabled,
    "issue": args.issue,
    "modifiedBy": args.modified_by,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/pipelines/checks/configurations/{RESOURCE_ID}", API_VERSION, project=PROJECT_ID)
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['createdBy', 'createdOn'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
