# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Create a new pull request.

.DESCRIPTION
    Calls  POST {org}/_apis/git/repositories/{repository_id}/pullrequests?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProjectId = $env:PROJECT_ID,

    [Parameter()]
    [string]$RepositoryId = $env:REPO_ID,

    [Parameter()]
    [string]$SourceBranch = $env:SOURCE_BRANCH,

    [Parameter()]
    [string]$TargetBranch = $env:TARGET_BRANCH,

    [Parameter()]
    [string]$PrTitle = $env:PR_TITLE,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProjectId' -Value $ProjectId
Assert-AdoEnv -Name 'RepositoryId' -Value $RepositoryId
Assert-AdoEnv -Name 'SourceBranch' -Value $SourceBranch
Assert-AdoEnv -Name 'TargetBranch' -Value $TargetBranch
Assert-AdoEnv -Name 'PrTitle' -Value $PrTitle
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    sourceRefName = $SourceBranch
    targetRefName = $TargetBranch
    title = $PrTitle
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/git/repositories/$RepositoryId/pullrequests" -ApiVersion $ApiVersion -Project $ProjectId

Write-Verbose "POST $uri"

$response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'pullRequestId') {
    Write-Warning "Unexpected response shape — missing 'pullRequestId'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'title') {
    Write-Warning "Unexpected response shape — missing 'title'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Pull request #$($response.pullRequestId) created: $($response.title)"
$response | ConvertTo-Json -Depth 5
