#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Delete (recycle) a work item.
#
# API:  DELETE {org}/_apis/wit/workitems/{work_item_id}?api-version=7.2-preview.3
# Auth: Basic (PAT)
#
# Usage: WORK_ITEM_ID="value" bash delete_work_item.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/delete?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2-preview.3"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
WORK_ITEM_ID=$(ado_require_env "WORK_ITEM_ID" "Work item ID (integer)")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/wit/workitems/${WORK_ITEM_ID}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X DELETE \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "code"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Work item {id} deleted (moved to recycle bin)"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
