# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Delete (recycle) a work item.

.DESCRIPTION
    Calls  DELETE {org}/_apis/wit/workitems/{work_item_id}?api-version=7.2-preview.3
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/delete?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$WorkItemId = $env:WORK_ITEM_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'WorkItemId' -Value $WorkItemId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2-preview.3'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/wit/workitems/$WorkItemId" -ApiVersion $ApiVersion

Write-Verbose "DELETE $uri"

$response = Invoke-RestMethod -Uri $uri -Method Delete -Headers $headers -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'id') {
    Write-Warning "Unexpected response shape — missing 'id'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'code') {
    Write-Warning "Unexpected response shape — missing 'code'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Work item $($response.id) deleted (moved to recycle bin)"
$response | ConvertTo-Json -Depth 5
