#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update a thread in a pull request.
#
# API:  PATCH {org}/_apis/git/repositories/{repository_id}/pullRequests/{pull_request_id}/threads/{thread_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: REPO_ID="value" PULL_REQUEST_ID="value" THREAD_ID="value" bash update_pull_request_threads.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
REPO_ID=$(ado_require_env "REPO_ID" "The repository ID of the pull request's target branch.")
PULL_REQUEST_ID=$(ado_require_env "PULL_REQUEST_ID" "ID of the pull request.")
THREAD_ID=$(ado_require_env "THREAD_ID" "ID of the thread to update.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "pullRequestThreadContext": "${PULL_REQUEST_THREAD_CONTEXT}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/git/repositories/${REPO_ID}/pullRequests/${PULL_REQUEST_ID}/threads/${THREAD_ID}" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "pullRequestThreadContext"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
