# AUTO-GENERATED by _generator — do not edit by hand.
<#
.SYNOPSIS
    Pester offline unit tests for New-Merge.ps1

.DESCRIPTION
    Mocks Invoke-RestMethod to validate URL construction,
    auth headers, response parsing, and error handling.
#>

BeforeAll {
    $ScriptPath = Join-Path $PSScriptRoot '..' 'New-Merge.ps1'
    $FixturePath = Join-Path $PSScriptRoot 'fixtures'
    $ProjectGuid = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
}

Describe 'New-Merge.ps1' -Tag 'Offline', 'Git' {

    Context 'Input validation' {

        It 'Throws when Organisation is empty' {
            {
                & $ScriptPath -Organization '' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when ProjectId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -ProjectId '' -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when RepositoryNameOrId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId '' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when Pat is empty' {
            {
                & $ScriptPath -Organization 'testorg' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat ''
            } | Should -Throw '*is required*'
        }
    }

    Context 'Successful API call (mocked)' {

        BeforeAll {
            $fixture = Get-Content (Join-Path $FixturePath 'create_merges_200.json') -Raw | ConvertFrom-Json
        }

        It 'Calls the correct URL' {
            Mock Invoke-RestMethod { return $fixture } -Verifiable

            & $ScriptPath -Organization 'testorg' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -InvokeVerifiable
            Should -Invoke Invoke-RestMethod -Times 1 -Exactly -ParameterFilter {
                $Uri -eq "https://dev.azure.com/testorg/$ProjectGuid/_apis/git/repositories/testvalue/merges?api-version=7.2" -and
                $Method -eq 'Post'
            }
        }

        It 'Sends correct Authorization header' {
            $expectedAuth = [Convert]::ToBase64String(
                [Text.Encoding]::ASCII.GetBytes(':fakepat')
            )

            Mock Invoke-RestMethod { return $fixture }

            & $ScriptPath -Organization 'testorg' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -Invoke Invoke-RestMethod -Times 1 -ParameterFilter {
                $Headers['Authorization'] -eq "Basic $expectedAuth"
            }
        }
    }

    Context 'HTTP error handling' {

        It 'Throws on 404 (not found)' {
            Mock Invoke-RestMethod {
                $ex = [System.Net.WebException]::new('The remote server returned an error: (404) Not Found.')
                throw $ex
            }

            { & $ScriptPath -Organization 'testorg' -ProjectId $ProjectGuid -Comment 'testvalue' -Parents 'testvalue' -RepositoryNameOrId 'testvalue' -Pat 'fakepat' } | Should -Throw
        }
    }
}
