#!/usr/bin/env bats
# AUTO-GENERATED by _generator — do not edit by hand.
# ============================================================================
# Offline unit tests for delete_variablegroups.sh
#
# Uses a stubbed curl function to intercept HTTP calls and return fixture data.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
FIXTURES_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/fixtures" && pwd)"

setup() {
    export AZURE_DEVOPS_ORG="testorg"
    export AZURE_DEVOPS_PAT="fakepat1234567890"
    export GROUP_ID="test-value-group_id"
    export PROJECT_IDS="test-value-project_ids"
    export FIXTURES_DIR
    export BATS_TMPDIR

    STUB_DIR="$(mktemp -d)"
    cat > "$STUB_DIR/curl" << STUBEOF
#!/usr/bin/env bash
echo "\$@" >> "${BATS_TMPDIR}/curl_args.log"
for arg in "\$@"; do
    if [[ "\$arg" == *"/_apis/distributedtask"*"api-version="* ]]; then
        cat "${FIXTURES_DIR}/delete_variablegroups_200.json"
        exit 0
    fi
done
echo '{"error": "no matching stub"}'
exit 1
STUBEOF
    chmod +x "$STUB_DIR/curl"
    export ORIGINAL_PATH="$PATH"
    export PATH="$STUB_DIR:$PATH"
    export STUB_DIR
    : > "${BATS_TMPDIR}/curl_args.log"
}

teardown() {
    export PATH="$ORIGINAL_PATH"
    rm -rf "$STUB_DIR"
    rm -f "${BATS_TMPDIR}/curl_args.log"
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@test "delete_variablegroups.sh: exits with error when AZURE_DEVOPS_ORG is unset" {
    unset AZURE_DEVOPS_ORG
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -ne 0 ]
    [[ "$output" == *"AZURE_DEVOPS_ORG"* ]]
}

@test "delete_variablegroups.sh: exits with error when AZURE_DEVOPS_PAT is unset" {
    unset AZURE_DEVOPS_PAT
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -ne 0 ]
    [[ "$output" == *"AZURE_DEVOPS_PAT"* ]]
}

@test "delete_variablegroups.sh: exits with error when GROUP_ID is unset" {
    unset GROUP_ID
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -ne 0 ]
    [[ "$output" == *"GROUP_ID"* ]]
}

@test "delete_variablegroups.sh: exits with error when PROJECT_IDS is unset" {
    unset PROJECT_IDS
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -ne 0 ]
    [[ "$output" == *"PROJECT_IDS"* ]]
}

@test "delete_variablegroups.sh: succeeds with valid env and stubbed curl" {
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -eq 0 ]
}

@test "delete_variablegroups.sh: sends Authorization header" {
    run bash "$SCRIPT_DIR/delete_variablegroups.sh"
    [ "$status" -eq 0 ]

    curl_args=$(cat "${BATS_TMPDIR}/curl_args.log")
    [[ "$curl_args" == *"Authorization: Basic"* ]]
}
