#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Creates a new personal access token (PAT) for the requesting user.

API:  POST {org}/_apis/tokens/pats?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/pats/create?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Creates a new personal access token (PAT) for the requesting user.")
parser.add_argument("--all-orgs", required=False, help="True, if this personal access token (PAT) is for all of the user's accessible organizations. Fals...")
parser.add_argument("--display-name", required=False, help="The token name")
parser.add_argument("--scope", required=False, help="The token scopes for accessing Azure DevOps resources")
parser.add_argument("--valid-to", required=False, help="The token expiration date. If the 'Enforce maximum personal access token lifespan' policy is enab...")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_pats", PAT)
logger.info("Creates a new personal access token (PAT) for the requesting user.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "allOrgs": args.all_orgs,
    "displayName": args.display_name,
    "scope": args.scope,
    "validTo": args.valid_to,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/tokens/pats", API_VERSION, base_host="vssps.dev.azure.com")
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['patToken', 'patTokenError'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
