# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Create a log and connect it to a pipeline run's execution plan.

.DESCRIPTION
    Calls  POST {org}/{scope_identifier}/_apis/distributedtask/hubs/{hub_name}/plans/{plan_id}/logs?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/logs/create?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$CreatedOn,

    [Parameter(Mandatory)]
    [string]$IndexLocation,

    [Parameter(Mandatory)]
    [string]$LastChangedOn,

    [Parameter(Mandatory)]
    [string]$LineCount,

    [Parameter(Mandatory)]
    [string]$Path,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ScopeIdentifier = $env:SCOPE_IDENTIFIER,

    [Parameter()]
    [string]$HubName = $env:HUB_NAME,

    [Parameter()]
    [string]$PlanId = $env:PLAN_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ScopeIdentifier' -Value $ScopeIdentifier
Assert-AdoEnv -Name 'HubName' -Value $HubName
Assert-AdoEnv -Name 'PlanId' -Value $PlanId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    createdOn = $CreatedOn
    indexLocation = $IndexLocation
    lastChangedOn = $LastChangedOn
    lineCount = $LineCount
    path = $Path
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "$ScopeIdentifier/_apis/distributedtask/hubs/$HubName/plans/$PlanId/logs" -ApiVersion $ApiVersion

Write-Verbose "POST $uri"

$response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'createdOn') {
    Write-Warning "Unexpected response shape — missing 'createdOn'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'indexLocation') {
    Write-Warning "Unexpected response shape — missing 'indexLocation'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
