#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Edit a process of a specific ID.

API:  PATCH {org}/_apis/work/processes/{process_type_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/processes/edit-process?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROCESS_TYPE_ID = get_env_or_exit("PROCESS_TYPE_ID", "processTypeId")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Edit a process of a specific ID.")
parser.add_argument("--description", required=False, help="New description of the process")
parser.add_argument("--is-default", required=False, help="If true new projects will use this process by default")
parser.add_argument("--is-enabled", required=False, help="If false the process will be disabled and cannot be used to create projects")
parser.add_argument("--name", required=False, help="New name of the process")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_edit_process", PAT)
logger.info("Edit a process of a specific ID.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "description": args.description,
    "isDefault": args.is_default,
    "isEnabled": args.is_enabled,
    "name": args.name,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/work/processes/{PROCESS_TYPE_ID}", API_VERSION)
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['name', 'customizationType'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(f"Processes: {data.get("name", "N/A")}")
print(json.dumps(data, indent=2))
