#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Get release for a given revision number.
#
# API:  GET {org}/_apis/release/releases/{release_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: RELEASE_ID="value" DEFINITION_SNAPSHOT_REVISION="value" bash get_release_revision.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/release/releases/get-release-revision?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
RELEASE_ID=$(ado_require_env "RELEASE_ID" "Id of the release.")
DEFINITION_SNAPSHOT_REVISION=$(ado_require_env "DEFINITION_SNAPSHOT_REVISION" "Definition snapshot revision number.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/release/releases/${RELEASE_ID}" "$API_VERSION" "$PROJECT" "vsrm.dev.azure.com")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
