#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Tells whether promote has completed for the specified promote job ID.
#
# API:  GET {org}/_apis/work/processadmin/processes/status/{id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: RESOURCE_ID="value" bash get_import_process_template_status.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processadmin/processes/import-process-template-status?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
RESOURCE_ID=$(ado_require_env "RESOURCE_ID" "The ID of the promote job operation")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processadmin/processes/status/${RESOURCE_ID}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "complete"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Processes ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
