# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Delete a service principal from the account.

.DESCRIPTION
    Calls  DELETE {org}/_apis/serviceprincipalentitlements/{service_principal_id}?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/member-entitlement-management/service-principal-entitlements/delete?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ServicePrincipalId = $env:SERVICE_PRINCIPAL_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ServicePrincipalId' -Value $ServicePrincipalId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/serviceprincipalentitlements/$ServicePrincipalId" -ApiVersion $ApiVersion -BaseHost "vsaex.dev.azure.com"

Write-Verbose "DELETE $uri"

$response = Invoke-RestMethod -Uri $uri -Method Delete -Headers $headers -ContentType 'application/json'

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
