# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Updates an existing folder at given existing path.

.DESCRIPTION
    Calls  PATCH {org}/_apis/release/folders/{path}?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/release/folders/update?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$CreatedBy,

    [Parameter(Mandatory)]
    [string]$CreatedOn,

    [Parameter(Mandatory)]
    [string]$Description,

    [Parameter(Mandatory)]
    [string]$LastChangedBy,

    [Parameter(Mandatory)]
    [string]$LastChangedDate,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProjectId = $env:PROJECT_ID,

    [Parameter()]
    [string]$Path = $env:PATH,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProjectId' -Value $ProjectId
Assert-AdoEnv -Name 'Path' -Value $Path
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    createdBy = $CreatedBy
    createdOn = $CreatedOn
    description = $Description
    lastChangedBy = $LastChangedBy
    lastChangedDate = $LastChangedDate
    path = $Path
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/release/folders/$Path" -ApiVersion $ApiVersion -Project $ProjectId -BaseHost "vsrm.dev.azure.com"

Write-Verbose "PATCH $uri"

$response = Invoke-RestMethod -Uri $uri -Method Patch -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'createdBy') {
    Write-Warning "Unexpected response shape — missing 'createdBy'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'createdOn') {
    Write-Warning "Unexpected response shape — missing 'createdOn'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
