#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update an existing classification node.
#
# API:  PATCH {org}/_apis/wit/classificationnodes/{structure_group}/{path}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: STRUCTURE_GROUP="value" CLASSIFICATION_PATH="value" bash update_classification_nodes.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/classification-nodes/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
STRUCTURE_GROUP=$(ado_require_env "STRUCTURE_GROUP" "Structure group of the classification node, area or iteration.")
CLASSIFICATION_PATH=$(ado_require_env "CLASSIFICATION_PATH" "Path of the classification node.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "attributes": "${ATTRIBUTES}",
  "children": "${CHILDREN}",
  "hasChildren": "${HAS_CHILDREN}",
  "id": "${RESOURCE_ID}",
  "identifier": "${IDENTIFIER}",
  "name": "${NAME}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/wit/classificationnodes/${STRUCTURE_GROUP}/${CLASSIFICATION_PATH}" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "name" "attributes"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Classification Nodes: {name}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
