# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Revokes the listed OAuth authorizations.

.DESCRIPTION
    Calls  POST {org}/_apis/tokenadmin/revocations?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/token-admin/revocations/revoke-authorizations?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/tokenadmin/revocations" -ApiVersion $ApiVersion -BaseHost "vssps.dev.azure.com"

Write-Verbose "POST $uri"

$response = Invoke-AdoRestMethod -Uri $uri -Method Post -Headers $headers -ExpectedStatusCode 204

#--- Output -----------------------------------------------------------------
if ($response.StatusCode -eq 204) {
    Write-Host "Revocations operation completed successfully."
} else {
    Write-Warning "Unexpected status code: $($response.StatusCode)"
}
