# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Update a variable group.

.DESCRIPTION
    Calls  PUT {org}/_apis/distributedtask/variablegroups/{group_id}?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/variablegroups/update?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$Description,

    [Parameter(Mandatory)]
    [string]$Name,

    [Parameter(Mandatory)]
    [string]$ProviderData,

    [Parameter(Mandatory)]
    [string]$Type,

    [Parameter(Mandatory)]
    [string]$VariableGroupProjectReferences,

    [Parameter(Mandatory)]
    [string]$Variables,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$GroupId = $env:GROUP_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'GroupId' -Value $GroupId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    description = $Description
    name = $Name
    providerData = $ProviderData
    type = $Type
    variableGroupProjectReferences = $VariableGroupProjectReferences
    variables = $Variables
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/distributedtask/variablegroups/$GroupId" -ApiVersion $ApiVersion

Write-Verbose "PUT $uri"

$response = Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'id') {
    Write-Warning "Unexpected response shape — missing 'id'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'name') {
    Write-Warning "Unexpected response shape — missing 'name'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'createdBy') {
    Write-Warning "Unexpected response shape — missing 'createdBy'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
Write-Host "Variablegroups: $($response.name)"
$response | ConvertTo-Json -Depth 5
