#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Add a variable group.
#
# API:  PATCH {org}/_apis/distributedtask/variablegroups?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: VARIABLE_GROUP_ID="value" bash update_share_variable_group.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/variablegroups/share-variable-group?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
VARIABLE_GROUP_ID=$(ado_require_env "VARIABLE_GROUP_ID" "variableGroupId")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/distributedtask/variablegroups" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
