#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# List all comments on a work item.
#
# API:  GET {org}/_apis/wit/workitems/{work_item_id}/comments?api-version=7.2-preview.4
# Auth: Basic (PAT)
#
# Usage: WORK_ITEM_ID="value" bash list_comments.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/comments/list?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2-preview.4"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
WORK_ITEM_ID=$(ado_require_env "WORK_ITEM_ID" "Work item ID (integer)")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/wit/workitems/${WORK_ITEM_ID}/comments" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "count" "comments"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
