# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Update for Diagnostics

.DESCRIPTION
    Calls  PUT {org}/_apis/hooks/subscriptions/{subscription_id}/diagnostics?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/hooks/diagnostics/update?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$DeliveryResults,

    [Parameter(Mandatory)]
    [string]$DeliveryTracing,

    [Parameter(Mandatory)]
    [string]$EvaluationTracing,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$SubscriptionId = $env:SUBSCRIPTION_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'SubscriptionId' -Value $SubscriptionId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    deliveryResults = $DeliveryResults
    deliveryTracing = $DeliveryTracing
    evaluationTracing = $EvaluationTracing
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/hooks/subscriptions/$SubscriptionId/diagnostics" -ApiVersion $ApiVersion

Write-Verbose "PUT $uri"

$response = Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'deliveryResults') {
    Write-Warning "Unexpected response shape — missing 'deliveryResults'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'deliveryTracing') {
    Write-Warning "Unexpected response shape — missing 'deliveryTracing'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
