#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# GetTaskAttachments API is deprecated.
#
# API:  GET {org}/_apis/release/releases/{release_id}/environments/{environment_id}/attempts/{attempt_id}/timelines/{timeline_id}/attachments/{type}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: RELEASE_ID="value" ENVIRONMENT_ID="value" ATTEMPT_ID="value" TIMELINE_ID="value" TYPE="value" bash get_task_attachments.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/release/attachments/get-task-attachments?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
RELEASE_ID=$(ado_require_env "RELEASE_ID" "Id of the release.")
ENVIRONMENT_ID=$(ado_require_env "ENVIRONMENT_ID" "Id of the release environment.")
ATTEMPT_ID=$(ado_require_env "ATTEMPT_ID" "Attempt number of deployment.")
TIMELINE_ID=$(ado_require_env "TIMELINE_ID" "Timeline Id of the task.")
TYPE=$(ado_require_env "TYPE" "Type of the attachment.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/release/releases/${RELEASE_ID}/environments/${ENVIRONMENT_ID}/attempts/${ATTEMPT_ID}/timelines/${TIMELINE_ID}/attachments/${TYPE}" "$API_VERSION" "$PROJECT" "vsrm.dev.azure.com")

RESPONSE=$(curl --silent --fail --show-error \
    -X GET \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    "$URL")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
