#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Get the widget metadata satisfying the specified contribution ID.

API:  GET {org}/_apis/dashboard/widgettypes/{contribution_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/dashboard/widget-types/get-widget-metadata?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
CONTRIBUTION_ID = get_env_or_exit("CONTRIBUTION_ID", "The ID of Contribution for the Widget")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("get_widget_metadata", PAT)
logger.info("Get the widget metadata satisfying the specified contribution ID.")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/dashboard/widgettypes/{CONTRIBUTION_ID}", API_VERSION, project=PROJECT_ID)
logger.info(f"GET {url}")

response = execute_request("GET", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['uri', 'widgetMetadata'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
