# AUTO-GENERATED by _generator — do not edit by hand.
<#
.SYNOPSIS
    Pester offline unit tests for Add-Group.ps1

.DESCRIPTION
    Mocks Invoke-RestMethod to validate URL construction,
    auth headers, response parsing, and error handling.
#>

BeforeAll {
    $ScriptPath = Join-Path $PSScriptRoot '..' 'Add-Group.ps1'
    $FixturePath = Join-Path $PSScriptRoot 'fixtures'
}

Describe 'Add-Group.ps1' -Tag 'Offline', 'Processes' {

    Context 'Input validation' {

        It 'Throws when Organisation is empty' {
            {
                & $ScriptPath -Organization '' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when ProcessId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId '' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when WitRefName is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName '' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when PageId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId '' -SectionId 'testvalue' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when SectionId is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId '' -Pat 'fakepat'
            } | Should -Throw '*is required*'
        }

        It 'Throws when Pat is empty' {
            {
                & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat ''
            } | Should -Throw '*is required*'
        }
    }

    Context 'Successful API call (mocked)' {

        BeforeAll {
            $fixture = Get-Content (Join-Path $FixturePath 'create_groups_200.json') -Raw | ConvertFrom-Json
        }

        It 'Calls the correct URL' {
            Mock Invoke-RestMethod { return $fixture } -Verifiable

            & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -InvokeVerifiable
            Should -Invoke Invoke-RestMethod -Times 1 -Exactly -ParameterFilter {
                $Uri -eq "https://dev.azure.com/testorg/_apis/work/processes/testvalue/workItemTypes/testvalue/layout/pages/testvalue/sections/testvalue/groups?api-version=7.2" -and
                $Method -eq 'Post'
            }
        }

        It 'Sends correct Authorization header' {
            $expectedAuth = [Convert]::ToBase64String(
                [Text.Encoding]::ASCII.GetBytes(':fakepat')
            )

            Mock Invoke-RestMethod { return $fixture }

            & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat' | Out-Null

            Should -Invoke Invoke-RestMethod -Times 1 -ParameterFilter {
                $Headers['Authorization'] -eq "Basic $expectedAuth"
            }
        }
    }

    Context 'HTTP error handling' {

        It 'Throws on 404 (not found)' {
            Mock Invoke-RestMethod {
                $ex = [System.Net.WebException]::new('The remote server returned an error: (404) Not Found.')
                throw $ex
            }

            { & $ScriptPath -Organization 'testorg' -Contribution 'testvalue' -Controls 'testvalue' -Height 'testvalue' -Id 'testvalue' -Inherited 'testvalue' -IsContribution 'testvalue' -ProcessId 'testvalue' -WitRefName 'testvalue' -PageId 'testvalue' -SectionId 'testvalue' -Pat 'fakepat' } | Should -Throw
        }
    }
}
