#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Create a new elastic pool.
#
# API:  POST {org}/_apis/distributedtask/elasticpools?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: POOL_NAME="value" bash create_elasticpools.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/elasticpools/create?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
POOL_NAME=$(ado_require_env "POOL_NAME" "Name to use for the new TaskAgentPool")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "agentInteractiveUI": "${AGENT_INTERACTIVE_UI}",
  "azureId": "${AZURE_ID}",
  "desiredIdle": "${DESIRED_IDLE}",
  "desiredSize": "${DESIRED_SIZE}",
  "maxCapacity": "${MAX_CAPACITY}",
  "maxSavedNodeCount": "${MAX_SAVED_NODE_COUNT}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/distributedtask/elasticpools" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X POST \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "agentPool" "agentQueue"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
