# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Update settings on a specified Elastic Pool.

.DESCRIPTION
    Calls  PATCH {org}/_apis/distributedtask/elasticpools/{pool_id}?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/distributed-task/elasticpools/update?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$AgentInteractiveUi,

    [Parameter(Mandatory)]
    [string]$AzureId,

    [Parameter(Mandatory)]
    [string]$DesiredIdle,

    [Parameter(Mandatory)]
    [string]$MaxCapacity,

    [Parameter(Mandatory)]
    [string]$MaxSavedNodeCount,

    [Parameter(Mandatory)]
    [string]$OrchestrationType,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$PoolId = $env:POOL_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'PoolId' -Value $PoolId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    agentInteractiveUI = $AgentInteractiveUi
    azureId = $AzureId
    desiredIdle = $DesiredIdle
    maxCapacity = $MaxCapacity
    maxSavedNodeCount = $MaxSavedNodeCount
    orchestrationType = $OrchestrationType
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/distributedtask/elasticpools/$PoolId" -ApiVersion $ApiVersion

Write-Verbose "PATCH $uri"

$response = Invoke-RestMethod -Uri $uri -Method Patch -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'agentInteractiveUI') {
    Write-Warning "Unexpected response shape — missing 'agentInteractiveUI'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'azureId') {
    Write-Warning "Unexpected response shape — missing 'azureId'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
