#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Removes a group from the work item form

API:  DELETE {org}/_apis/work/processdefinitions/{process_id}/workItemTypes/{wit_ref_name}/layout/pages/{page_id}/sections/{section_id}/groups/{group_id}?api-version=4.1
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/process-definitions/remove-group/remove-group?view=azure-devops-rest-7.2
"""

import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "4.1"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROCESS_ID = get_env_or_exit("PROCESS_ID", "The ID of the process")
WIT_REF_NAME = get_env_or_exit("WIT_REF_NAME", "The reference name of the work item type")
PAGE_ID = get_env_or_exit("PAGE_ID", "The ID of the page the group is in")
SECTION_ID = get_env_or_exit("SECTION_ID", "The ID of the section to the group is in")
GROUP_ID = get_env_or_exit("GROUP_ID", "The ID of the group")

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("delete_group", PAT)
logger.info("Removes a group from the work item form")

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/work/processdefinitions/{PROCESS_ID}/workItemTypes/{WIT_REF_NAME}/layout/pages/{PAGE_ID}/sections/{SECTION_ID}/groups/{GROUP_ID}", API_VERSION)
logger.info(f"DELETE {url}")

response = execute_request("DELETE", url, HEADERS)

data = response.json()

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
