#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Create debug entries for a symbol request as specified by its identifier.

API:  POST {org}/_apis/symbol/requests/{request_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/symbol/requests/create-requests-request-id-debug-entries?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
REQUEST_ID = get_env_or_exit("REQUEST_ID", "The symbol request identifier.")
COLLECTION = get_env_or_exit("COLLECTION", "A valid debug entry collection name. Must be 'debugentries'.")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Create debug entries for a symbol request as specified by its identifier.")
parser.add_argument("--create-behavior", required=False, help="Defines what to do when a debug entry in the batch already exists.")
parser.add_argument("--debug-entries", required=False, help="The debug entries.")
parser.add_argument("--proof-nodes", required=False, help="Serialized Proof nodes, used to verify uploads on server side for Chunk Dedup DebugEntry")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_requests_request_id_debug_entries", PAT)
logger.info("Create debug entries for a symbol request as specified by its identifier.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "createBehavior": args.create_behavior,
    "debugEntries": args.debug_entries,
    "proofNodes": args.proof_nodes,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/symbol/requests/{REQUEST_ID}", API_VERSION, base_host="artifacts.dev.azure.com")
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
