#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Restores the deleted work item from Recycle Bin.
#
# API:  PATCH {org}/_apis/wit/recyclebin/{id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: RESOURCE_ID="value" bash update_restore_work_item.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/recyclebin/restore-work-item?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
RESOURCE_ID=$(ado_require_env "RESOURCE_ID" "ID of the work item to be restored")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "isDeleted": "${IS_DELETED}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/wit/recyclebin/${RESOURCE_ID}" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "resource"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
