#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Updates a work item type of the process.
#
# API:  PATCH {org}/_apis/work/processdefinitions/{process_id}/workitemtypes/{wit_ref_name}?api-version=4.1
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" WIT_REF_NAME="value" bash update_work_item_type.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/process-definitions/update-work-item-type/update-work-item-type?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="4.1"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "The ID of the process")
WIT_REF_NAME=$(ado_require_env "WIT_REF_NAME" "The reference name of the work item type")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "color": "${COLOR}",
  "description": "${DESCRIPTION}",
  "icon": "${ICON}",
  "isDisabled": "${IS_DISABLED}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processdefinitions/${PROCESS_ID}/workitemtypes/${WIT_REF_NAME}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "name" "behaviors"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Update Work Item Type ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
