# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
<#
.SYNOPSIS
    Publish Test Result Document for Result Document

.DESCRIPTION
    Calls  POST {org}/_apis/testresults/runs/{run_id}/resultdocument?api-version=7.2
    Uses Basic Auth with a PAT stored in $env:AZURE_DEVOPS_PAT.

.LINK
    https://learn.microsoft.com/en-us/rest/api/azure/devops/test-results/result-document/publish-test-result-document?view=azure-devops-rest-7.2
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$OperationReference,

    [Parameter(Mandatory)]
    [string]$Payload,

    [Parameter()]
    [string]$Organization = $env:AZURE_DEVOPS_ORG,

    [Parameter()]
    [string]$ProjectId = $env:PROJECT_ID,

    [Parameter()]
    [string]$RunId = $env:RUN_ID,

    [Parameter()]
    [string]$Pat = $env:AZURE_DEVOPS_PAT
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#--- Shared helpers ---------------------------------------------------------
$_sharedDir = Join-Path (Join-Path (Split-Path $PSScriptRoot -Parent) '..') '_shared'
. (Join-Path $_sharedDir 'AdoAuth.ps1')
. (Join-Path $_sharedDir 'AdoHttp.ps1')

#--- Validate inputs --------------------------------------------------------
Assert-AdoEnv -Name 'Organisation' -Value $Organization
Assert-AdoEnv -Name 'ProjectId' -Value $ProjectId
Assert-AdoEnv -Name 'RunId' -Value $RunId
Assert-AdoEnv -Name 'PAT' -Value $Pat

#--- API version ------------------------------------------------------------
$ApiVersion = '7.2'

#--- Build auth header ------------------------------------------------------
$headers = New-AdoAuthHeader -Pat $Pat

#--- Build request body -----------------------------------------------------
$body = @{
    operationReference = $OperationReference
    payload = $Payload
} | ConvertTo-Json -Depth 3

#--- Call the API -----------------------------------------------------------
$uri = New-AdoUrl -Organization $Organization -Path "_apis/testresults/runs/$RunId/resultdocument" -ApiVersion $ApiVersion -Project $ProjectId -BaseHost "vstmr.dev.azure.com"

Write-Verbose "POST $uri"

$response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ContentType 'application/json'

#--- Version guard ----------------------------------------------------------
if ($response.PSObject.Properties.Name -notcontains 'operationReference') {
    Write-Warning "Unexpected response shape — missing 'operationReference'. The server may not support api-version $ApiVersion."
}
if ($response.PSObject.Properties.Name -notcontains 'payload') {
    Write-Warning "Unexpected response shape — missing 'payload'. The server may not support api-version $ApiVersion."
}

#--- Output -----------------------------------------------------------------
$response | ConvertTo-Json -Depth 5
