#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Moves a control to a new group
#
# API:  PUT {org}/_apis/work/processdefinitions/{process_id}/workItemTypes/{wit_ref_name}/layout/groups/{group_id}/controls/{control_id}?api-version=4.1
# Auth: Basic (PAT)
#
# Usage: PROCESS_ID="value" WIT_REF_NAME="value" GROUP_ID="value" CONTROL_ID="value" bash set_control_in_group.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/process-definitions/set-control-in-group/set-control-in-group?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="4.1"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROCESS_ID=$(ado_require_env "PROCESS_ID" "The ID of the process")
WIT_REF_NAME=$(ado_require_env "WIT_REF_NAME" "The reference name of the work item type")
GROUP_ID=$(ado_require_env "GROUP_ID" "The ID of the group to move the control to")
CONTROL_ID=$(ado_require_env "CONTROL_ID" "The id of the control")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "contribution": "${CONTRIBUTION}",
  "controlType": "${CONTROL_TYPE}",
  "height": "${HEIGHT}",
  "id": "${RESOURCE_ID}",
  "inherited": "${INHERITED}",
  "isContribution": "${IS_CONTRIBUTION}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/work/processdefinitions/${PROCESS_ID}/workItemTypes/${WIT_REF_NAME}/layout/groups/${GROUP_ID}/controls/${CONTROL_ID}" "$API_VERSION")

RESPONSE=$(curl --silent --fail --show-error \
    -X PUT \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "contribution"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Set Control In Group ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
