#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Create a widget on the specified dashboard.

API:  POST {org}/{team}/_apis/dashboard/dashboards/{dashboard_id}/widgets?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/dashboard/widgets/create?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
DASHBOARD_ID = get_env_or_exit("DASHBOARD_ID", "ID of dashboard the widget will be added to.")
TEAM_ID = get_env_or_exit("TEAM_ID", "Team ID or team name")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Create a widget on the specified dashboard.")
parser.add_argument("--allowed-sizes", required=False, help="Refers to the allowed sizes for the widget. This gets populated when user wants to configure the ...")
parser.add_argument("--are-settings-blocked-for-user", required=False, help="Read-Only Property from Dashboard Service. Indicates if settings are blocked for the current user.")
parser.add_argument("--artifact-id", required=False, help="Refers to unique identifier of a feature artifact. Used for pinning+unpinning a specific artifact.")
parser.add_argument("--configuration-contribution-id", required=False, help="configurationContributionId")
parser.add_argument("--configuration-contribution-relative-id", required=False, help="configurationContributionRelativeId")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_widgets", PAT)
logger.info("Create a widget on the specified dashboard.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "allowedSizes": args.allowed_sizes,
    "areSettingsBlockedForUser": args.are_settings_blocked_for_user,
    "artifactId": args.artifact_id,
    "configurationContributionId": args.configuration_contribution_id,
    "configurationContributionRelativeId": args.configuration_contribution_relative_id,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"{TEAM_ID}/_apis/dashboard/dashboards/{DASHBOARD_ID}/widgets", API_VERSION, project=PROJECT_ID)
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['id', 'name'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
