#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update the status of an alert
#
# API:  PATCH {org}/_apis/alert/repositories/{repository}/alerts/{alert_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: ALERT_ID="value" REPOSITORY="value" bash update_alerts.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/advanced-security/alerts/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
ALERT_ID=$(ado_require_env "ALERT_ID" "The ID of the alert")
REPOSITORY=$(ado_require_env "REPOSITORY" "The name or ID of the repository")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
BODY=$(cat <<EOF
{
  "dismissedComment": "${DISMISSED_COMMENT}",
  "dismissedReason": "${DISMISSED_REASON}",
  "state": "${STATE}"
}
EOF
)

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/alert/repositories/${REPOSITORY}/alerts/${ALERT_ID}" "$API_VERSION" "$PROJECT" "advsec.dev.azure.com")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "additionalProperties" "alertId"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
