#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update the diagnostics settings for a subscription.

API:  PUT {org}/_apis/notification/subscriptions/{subscription_id}/diagnostics?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/notification/diagnostics/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
SUBSCRIPTION_ID = get_env_or_exit("SUBSCRIPTION_ID", "The id of the notifications subscription.")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update the diagnostics settings for a subscription.")
parser.add_argument("--delivery-results", required=False, help="Diagnostics settings for retaining delivery results. Used for Service Hooks subscriptions.")
parser.add_argument("--delivery-tracing", required=False, help="Diagnostics settings for troubleshooting notification delivery.")
parser.add_argument("--evaluation-tracing", required=False, help="Diagnostics settings for troubleshooting event matching.")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_diagnostics", PAT)
logger.info("Update the diagnostics settings for a subscription.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "deliveryResults": args.delivery_results,
    "deliveryTracing": args.delivery_tracing,
    "evaluationTracing": args.evaluation_tracing,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/notification/subscriptions/{SUBSCRIPTION_ID}/diagnostics", API_VERSION, base_host="dev.azure.com")
logger.info(f"PUT {url}")

response = execute_request("PUT", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['deliveryResults', 'deliveryTracing'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
