#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Update test run by its ID.

API:  PATCH {org}/_apis/test/runs/{run_id}?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/update?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROJECT_ID = get_env_or_exit("PROJECT_ID", "project name or GUID")
RUN_ID = get_env_or_exit("RUN_ID", "ID of the run to update.")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Update test run by its ID.")
parser.add_argument("--build", required=False, help="An abstracted reference to the build that it belongs.")
parser.add_argument("--build-drop-location", required=False, help="Drop location of the build used for test run.")
parser.add_argument("--build-flavor", required=False, help="Flavor of the build used for test run. (E.g: Release, Debug)")
parser.add_argument("--build-platform", required=False, help="Platform of the build used for test run. (E.g.: x86, amd64)")
parser.add_argument("--comment", required=False, help="Comments entered by those analyzing the run.")
parser.add_argument("--completed-date", required=False, help="Completed date time of the run.")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("update_runs", PAT)
logger.info("Update test run by its ID.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "build": args.build,
    "buildDropLocation": args.build_drop_location,
    "buildFlavor": args.build_flavor,
    "buildPlatform": args.build_platform,
    "comment": args.comment,
    "completedDate": args.completed_date,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/test/runs/{RUN_ID}", API_VERSION, project=PROJECT_ID)
logger.info(f"PATCH {url}")

response = execute_request("PATCH", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['id', 'name', 'build'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
