#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Creates a control in a group.

API:  POST {org}/_apis/work/processes/{process_id}/workItemTypes/{wit_ref_name}/layout/groups/{group_id}/controls?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/processes/controls/create?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")
PROCESS_ID = get_env_or_exit("PROCESS_ID", "The ID of the process.")
WIT_REF_NAME = get_env_or_exit("WIT_REF_NAME", "The reference name of the work item type.")
GROUP_ID = get_env_or_exit("GROUP_ID", "The ID of the group to add the control to.")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Creates a control in a group.")
parser.add_argument("--contribution", required=False, help="Contribution for the control.")
parser.add_argument("--control-type", required=False, help="Type of the control.")
parser.add_argument("--height", required=False, help="Height of the control, for html controls.")
parser.add_argument("--id", required=False, help="The id for the layout node.")
parser.add_argument("--inherited", required=False, help="A value indicating whether this layout node has been inherited. from a parent layout. This is exp...")
parser.add_argument("--is-contribution", required=False, help="A value indicating if the layout node is contribution or not.")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("create_controls", PAT)
logger.info("Creates a control in a group.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "contribution": args.contribution,
    "controlType": args.control_type,
    "height": args.height,
    "id": args.id,
    "inherited": args.inherited,
    "isContribution": args.is_contribution,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/work/processes/{PROCESS_ID}/workItemTypes/{WIT_REF_NAME}/layout/groups/{GROUP_ID}/controls", API_VERSION)
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['id', 'contribution'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(f"Controls ID: {data.get("id", "N/A")}")
print(json.dumps(data, indent=2))
