#!/usr/bin/env bash
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
# ============================================================================
# Update a test variable by its ID.
#
# API:  PATCH {org}/_apis/testplan/variables/{test_variable_id}?api-version=7.2
# Auth: Basic (PAT)
#
# Usage: TEST_VARIABLE_ID="value" bash update_variables.sh
#
# Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/test-plan/variables/update?view=azure-devops-rest-7.2
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../_shared/common.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION="7.2"
ORG=$(ado_require_env "AZURE_DEVOPS_ORG" "organisation slug")
PAT=$(ado_require_env "AZURE_DEVOPS_PAT" "Personal Access Token")
PROJECT=$(ado_require_env "PROJECT_ID" "project name or GUID")
TEST_VARIABLE_ID=$(ado_require_env "TEST_VARIABLE_ID" "ID of the test variable to update.")

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
AUTH=$(ado_build_auth "$PAT")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
set +u
BODY=$(cat <<EOF
{
  "description": "${DESCRIPTION}",
  "name": "${NAME}",
  "values": "${VALUES}"
}
EOF
)
set -u

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
URL=$(ado_build_url "$ORG" "_apis/testplan/variables/${TEST_VARIABLE_ID}" "$API_VERSION" "$PROJECT")

RESPONSE=$(curl --silent --fail --show-error \
    -X PATCH \
    -H "Authorization: Basic ${AUTH}" \
    -H "Content-Type: application/json" \
    -d "$BODY" \
    "$URL")

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
ado_version_guard "$RESPONSE" "id" "project"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
echo "Variables ID: {id}"
echo "$RESPONSE" | python3 -m json.tool 2>/dev/null || echo "$RESPONSE"
