#!/usr/bin/env python3
# AUTO-GENERATED by _generator — do not edit by hand.
# Source of truth: _generator/definitions/
"""
Query for notifications.

API:  POST {org}/_apis/hooks/notificationsquery?api-version=7.2
Auth: Basic (PAT)

Docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/hooks/notifications/query?view=azure-devops-rest-7.2
"""

import argparse
import json
import os
import sys

# Add project root to path for shared helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

import requests

from _shared.auth import build_auth_header, get_env_or_exit
from _shared.logging_utils import AdoLogger
from _shared.http_client import build_url, execute_request, version_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
API_VERSION = "7.2"

ORGANIZATION = get_env_or_exit("AZURE_DEVOPS_ORG", "organisation slug")
PAT = get_env_or_exit("AZURE_DEVOPS_PAT", "Personal Access Token")

# ---------------------------------------------------------------------------
# CLI arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="Query for notifications.")
parser.add_argument("--associated-subscriptions", required=False, help="The subscriptions associated with the notifications returned from the query")
parser.add_argument("--include-details", required=False, help="If true, we will return all notification history for the query provided; otherwise, the summary i...")
parser.add_argument("--max-created-date", required=False, help="Optional maximum date at which the notification was created")
parser.add_argument("--max-results", required=False, help="Optional maximum number of overall results to include")
parser.add_argument("--max-results-per-subscription", required=False, help="Optional maximum number of results for each subscription. Only takes effect when a list of subscr...")
parser.add_argument("--min-created-date", required=False, help="Optional minimum date at which the notification was created")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Auth header & logging
# ---------------------------------------------------------------------------
HEADERS = build_auth_header(PAT)
logger = AdoLogger("query_notifications", PAT)
logger.info("Query for notifications.")

# ---------------------------------------------------------------------------
# Request body
# ---------------------------------------------------------------------------
body = {
    "associatedSubscriptions": args.associated_subscriptions,
    "includeDetails": args.include_details,
    "maxCreatedDate": args.max_created_date,
    "maxResults": args.max_results,
    "maxResultsPerSubscription": args.max_results_per_subscription,
    "minCreatedDate": args.min_created_date,
}

# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------
url = build_url(ORGANIZATION, f"_apis/hooks/notificationsquery", API_VERSION)
logger.info(f"POST {url}")

response = execute_request("POST", url, HEADERS, body=body)

data = response.json()

# ---------------------------------------------------------------------------
# Version guard
# ---------------------------------------------------------------------------
version_guard(data, ['associatedSubscriptions', 'includeDetails'], API_VERSION)

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
print(json.dumps(data, indent=2))
